### ISSUE TITLE
Can't create package "Git.Git" - Fails at Creating Proactive Remediation

### ISSUE THREAD

**Issue by flotpg** [FlorianSLZ/Intune-Win32-Deployer#16]
Hi.
I'm just starting to try your nice app - thanks a lot for the hard wort.

I'm struggling creating a package for Git:
![CleanShot 2023-08-24 at 02 27 14@2x](https://github.com/FlorianSLZ/Intune-Win32-Deployer/assets/20798074/19df7bac-b5a6-41a3-a4d3-39336a54e256)
```
Creating Proactive Remediation:
New-Item : Could not find a part of the path 'C:\Users\localadmin\AppData\Local\Intune-Win32-Deployer\Proactive
Remediations\winget upgrade - Git \detection-winget-upgrade.ps1'.
At C:\Users\localadmin\AppData\Local\Intune-Win32-Deployer\Intune-Win32-Deployer.ps1:526 char:32
+ ... on | Out-File (New-Item $PAR_detection_path -Type File -Force) -Encod ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\locala...get-upgrade.ps1:String) [New-Item], DirectoryNotFoundExce
   ption
    + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.NewItemCommand
```

Another package which also throws exceptions is "Notepad++.Notepad++".

Any hints?

Many thanks and best regards, Flo.

**Comment by flotpg** [comment]
Without "Create PR":
![CleanShot 2023-08-24 at 02 32 38@2x](https://github.com/FlorianSLZ/Intune-Win32-Deployer/assets/20798074/6d99cc76-2f90-4069-90dd-7d834ad1958a)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Management.Automation.CmdletInvocationException: Cannot process argument transformation on parameter 'ID'. Cannot convert value to type System.String. ---> System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ID'. Cannot convert value to type System.String. ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value to type System.String. ---> System.Management.Automation.PSInvalidCastException: Cannot convert value to type System.String.
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9167.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Microsoft.PowerShell.ConsoleHost
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Management.Automation
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.2003
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9167.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.PowerShell.Security
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.PowerShell.PSReadline
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Program%20Files/WindowsPowerShell/Modules/PSReadline/2.0.0/Microsoft.PowerShell.PSReadLine.dll
----------------------------------------
Microsoft.PowerShell.Commands.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
Microsoft.PowerShell.Commands.Utility
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9176.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.37.0.0
    Win32 Version: 4.37.0.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/MSAL.PS/4.37.0.0/Microsoft.Identity.Client.4.37.0/net45/Microsoft.Identity.Client.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.Identity.Client.Desktop
    Assembly Version: 4.37.0.0
    Win32 Version: 4.37.0.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/MSAL.PS/4.37.0.0/Microsoft.Identity.Client.Desktop.4.37.0/net461/Microsoft.Identity.Client.Desktop.dll
----------------------------------------
Windows.Security
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.Security.winmd
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.864.35
    Win32 Version: 1.0.864.35
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/MSAL.PS/4.37.0.0/Microsoft.Web.WebView2.1.0.864.35/net45/Microsoft.Web.WebView2.Core.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.864.35
    Win32 Version: 1.0.864.35
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/MSAL.PS/4.37.0.0/Microsoft.Web.WebView2.1.0.864.35/net45/Microsoft.Web.WebView2.WinForms.dll
----------------------------------------
Microsoft.Web.WebView2.Wpf
    Assembly Version: 1.0.864.35
    Win32 Version: 1.0.864.35
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/MSAL.PS/4.37.0.0/Microsoft.Web.WebView2.1.0.864.35/net45/Microsoft.Web.WebView2.Wpf.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
rkzugdj0
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
w3hme4v1
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.Graph.Authentication
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Microsoft.Graph.Authentication.dll
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Graph.Authentication.Core
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Microsoft.Graph.Authentication.Core.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/Newtonsoft.Json.dll
----------------------------------------
Azure.Core
    Assembly Version: 1.33.0.0
    Win32 Version: 1.3300.23.31609
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/Azure.Core.dll
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/System.Threading.Tasks.Extensions.dll
----------------------------------------
Microsoft.PowerShell.Commands.Diagnostics
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll
----------------------------------------
Microsoft.WSMan.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll
----------------------------------------
Microsoft.WSMan.Runtime
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22000.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Runtime/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Runtime.dll
----------------------------------------
Microsoft.Graph.Groups.private
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Groups/2.3.0/bin/Microsoft.Graph.Groups.private.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ComSnippets
    Assembly Version: 0.0.0.0
    Win32 Version: 10.0.22000.2003
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
System.Management.Automation.ComInterop.DynamicAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 10.0.22000.2003
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
Azure.Identity
    Assembly Version: 1.9.0.0
    Win32 Version: 1.900.23.26104
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Azure.Identity.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/System.Memory.dll
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.49.1.0
    Win32 Version: 4.49.1.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/Microsoft.Identity.Client.dll
----------------------------------------
Microsoft.Identity.Client.Extensions.Msal
    Assembly Version: 2.25.3.0
    Win32 Version: 2.25.3.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/Microsoft.Identity.Client.Extensions.Msal.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/System.Text.Json.dll
----------------------------------------
Azure.Identity.BrokeredAuthentication
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.22.40906
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Azure.Identity.BrokeredAuthentication.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/System.Buffers.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/System.Numerics.Vectors.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
Microsoft.IdentityModel.Abstractions
    Assembly Version: 6.31.0.0
    Win32 Version: 6.31.0.40607
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Microsoft.IdentityModel.Abstractions.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/System.Text.Encodings.Web.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 3.0.9.0
    Win32 Version: 3.0.9.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/Microsoft.Graph.Core.dll
----------------------------------------
Microsoft.Kiota.Authentication.Azure
    Assembly Version: 1.0.3.0
    Win32 Version: 1.0.3.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Microsoft.Kiota.Authentication.Azure.dll
----------------------------------------
Microsoft.Kiota.Abstractions
    Assembly Version: 1.1.4.0
    Win32 Version: 1.1.4.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Microsoft.Kiota.Abstractions.DLL
----------------------------------------
Microsoft.Kiota.Http.HttpClientLibrary
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Microsoft.Kiota.Http.HttpClientLibrary.dll
----------------------------------------
System.Net.Http.WinHttpHandler
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/localadmin/Documents/WindowsPowerShell/Modules/Microsoft.Graph.Authentication/2.3.0/Dependencies/Desktop/System.Net.Http.WinHttpHandler.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
